# Generated by Django 5.0.6 on 2024-05-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioskop', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='img/%y'),
        ),
    ]
